[tool.poetry]
name = "mersea"
version = "0.4.0"
description = "Mermaid diagram visual editor bridge"
authors = ["fedor"]
packages = [{include = "mersea"}]
include = ["mersea/assets/*"]

[tool.poetry.scripts]
mersea = "mersea.cli:main"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
